// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: dpki/v1/certificate.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Algorithm int32

const (
	Algorithm_ALGORITHM_UNSPECIFIED Algorithm = 0
	Algorithm_ALGORITHM_ECDSA_P256  Algorithm = 2
	Algorithm_ALGORITHM_ED25519     Algorithm = 1
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		2: "ALGORITHM_ECDSA_P256",
		1: "ALGORITHM_ED25519",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED": 0,
		"ALGORITHM_ECDSA_P256":  2,
		"ALGORITHM_ED25519":     1,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_dpki_v1_certificate_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_dpki_v1_certificate_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_dpki_v1_certificate_proto_rawDescGZIP(), []int{0}
}

type Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Algorithm     Algorithm              `protobuf:"varint,3,opt,name=algorithm,proto3,enum=dpki.v1.Algorithm" json:"algorithm,omitempty"`
	ValidFrom     int64                  `protobuf:"varint,4,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_dpki_v1_certificate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_dpki_v1_certificate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_dpki_v1_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *Certificate) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Certificate) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Certificate) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *Certificate) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *Certificate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_dpki_v1_certificate_proto protoreflect.FileDescriptor

const file_dpki_v1_certificate_proto_rawDesc = "" +
	"\n" +
	"\x19dpki/v1/certificate.proto\x12\adpki.v1\"\xaf\x01\n" +
	"\vCertificate\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x120\n" +
	"\talgorithm\x18\x03 \x01(\x0e2\x12.dpki.v1.AlgorithmR\talgorithm\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x04 \x01(\x03R\tvalidFrom\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion*W\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ALGORITHM_ECDSA_P256\x10\x02\x12\x15\n" +
	"\x11ALGORITHM_ED25519\x10\x01B6Z4github.com/ajablonsk1/blockchain-dpki/internal/typesb\x06proto3"

var (
	file_dpki_v1_certificate_proto_rawDescOnce sync.Once
	file_dpki_v1_certificate_proto_rawDescData []byte
)

func file_dpki_v1_certificate_proto_rawDescGZIP() []byte {
	file_dpki_v1_certificate_proto_rawDescOnce.Do(func() {
		file_dpki_v1_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dpki_v1_certificate_proto_rawDesc), len(file_dpki_v1_certificate_proto_rawDesc)))
	})
	return file_dpki_v1_certificate_proto_rawDescData
}

var file_dpki_v1_certificate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dpki_v1_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dpki_v1_certificate_proto_goTypes = []any{
	(Algorithm)(0),      // 0: dpki.v1.Algorithm
	(*Certificate)(nil), // 1: dpki.v1.Certificate
}
var file_dpki_v1_certificate_proto_depIdxs = []int32{
	0, // 0: dpki.v1.Certificate.algorithm:type_name -> dpki.v1.Algorithm
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dpki_v1_certificate_proto_init() }
func file_dpki_v1_certificate_proto_init() {
	if File_dpki_v1_certificate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dpki_v1_certificate_proto_rawDesc), len(file_dpki_v1_certificate_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dpki_v1_certificate_proto_goTypes,
		DependencyIndexes: file_dpki_v1_certificate_proto_depIdxs,
		EnumInfos:         file_dpki_v1_certificate_proto_enumTypes,
		MessageInfos:      file_dpki_v1_certificate_proto_msgTypes,
	}.Build()
	File_dpki_v1_certificate_proto = out.File
	file_dpki_v1_certificate_proto_goTypes = nil
	file_dpki_v1_certificate_proto_depIdxs = nil
}
