// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: dpki/v1/state.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DomainState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *Certificate           `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Revoked       bool                   `protobuf:"varint,3,opt,name=revoked,proto3" json:"revoked,omitempty"`
	RevokedAt     int64                  `protobuf:"varint,4,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	RevokeReason  string                 `protobuf:"bytes,5,opt,name=revoke_reason,json=revokeReason,proto3" json:"revoke_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainState) Reset() {
	*x = DomainState{}
	mi := &file_dpki_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainState) ProtoMessage() {}

func (x *DomainState) ProtoReflect() protoreflect.Message {
	mi := &file_dpki_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainState.ProtoReflect.Descriptor instead.
func (*DomainState) Descriptor() ([]byte, []int) {
	return file_dpki_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *DomainState) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *DomainState) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *DomainState) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *DomainState) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

func (x *DomainState) GetRevokeReason() string {
	if x != nil {
		return x.RevokeReason
	}
	return ""
}

var File_dpki_v1_state_proto protoreflect.FileDescriptor

const file_dpki_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x13dpki/v1/state.proto\x12\adpki.v1\x1a\x19dpki/v1/certificate.proto\"\xb9\x01\n" +
	"\vDomainState\x126\n" +
	"\vcertificate\x18\x01 \x01(\v2\x14.dpki.v1.CertificateR\vcertificate\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x18\n" +
	"\arevoked\x18\x03 \x01(\bR\arevoked\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x04 \x01(\x03R\trevokedAt\x12#\n" +
	"\rrevoke_reason\x18\x05 \x01(\tR\frevokeReasonB6Z4github.com/ajablonsk1/blockchain-dpki/internal/typesb\x06proto3"

var (
	file_dpki_v1_state_proto_rawDescOnce sync.Once
	file_dpki_v1_state_proto_rawDescData []byte
)

func file_dpki_v1_state_proto_rawDescGZIP() []byte {
	file_dpki_v1_state_proto_rawDescOnce.Do(func() {
		file_dpki_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dpki_v1_state_proto_rawDesc), len(file_dpki_v1_state_proto_rawDesc)))
	})
	return file_dpki_v1_state_proto_rawDescData
}

var file_dpki_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dpki_v1_state_proto_goTypes = []any{
	(*DomainState)(nil), // 0: dpki.v1.DomainState
	(*Certificate)(nil), // 1: dpki.v1.Certificate
}
var file_dpki_v1_state_proto_depIdxs = []int32{
	1, // 0: dpki.v1.DomainState.certificate:type_name -> dpki.v1.Certificate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dpki_v1_state_proto_init() }
func file_dpki_v1_state_proto_init() {
	if File_dpki_v1_state_proto != nil {
		return
	}
	file_dpki_v1_certificate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dpki_v1_state_proto_rawDesc), len(file_dpki_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dpki_v1_state_proto_goTypes,
		DependencyIndexes: file_dpki_v1_state_proto_depIdxs,
		MessageInfos:      file_dpki_v1_state_proto_msgTypes,
	}.Build()
	File_dpki_v1_state_proto = out.File
	file_dpki_v1_state_proto_goTypes = nil
	file_dpki_v1_state_proto_depIdxs = nil
}
