// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: dpki/v1/transaction.proto

package types

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Transaction_Register
	//	*Transaction_Revoke
	//	*Transaction_Rotate
	Body          isTransaction_Body `protobuf_oneof:"body"`
	Signature     []byte             `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	ChainId       string             `protobuf:"bytes,11,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (tx *Transaction) Reset() {
	*tx = Transaction{}
	mi := &file_dpki_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(tx))
	ms.StoreMessageInfo(mi)
}

func (tx *Transaction) String() string {
	return protoimpl.X.MessageStringOf(tx)
}

func (*Transaction) ProtoMessage() {}

func (tx *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_dpki_v1_transaction_proto_msgTypes[0]
	if tx != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(tx))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(tx)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_dpki_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (tx *Transaction) GetBody() isTransaction_Body {
	if tx != nil {
		return tx.Body
	}
	return nil
}

func (tx *Transaction) GetRegister() *RegisterTx {
	if tx != nil {
		if x, ok := tx.Body.(*Transaction_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (tx *Transaction) GetRevoke() *RevokeTx {
	if tx != nil {
		if x, ok := tx.Body.(*Transaction_Revoke); ok {
			return x.Revoke
		}
	}
	return nil
}

func (tx *Transaction) GetRotate() *RotateTx {
	if tx != nil {
		if x, ok := tx.Body.(*Transaction_Rotate); ok {
			return x.Rotate
		}
	}
	return nil
}

func (tx *Transaction) GetSignature() []byte {
	if tx != nil {
		return tx.Signature
	}
	return nil
}

func (tx *Transaction) GetChainId() string {
	if tx != nil {
		return tx.ChainId
	}
	return ""
}

type isTransaction_Body interface {
	isTransaction_Body()
}

type Transaction_Register struct {
	Register *RegisterTx `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type Transaction_Revoke struct {
	Revoke *RevokeTx `protobuf:"bytes,2,opt,name=revoke,proto3,oneof"`
}

type Transaction_Rotate struct {
	Rotate *RotateTx `protobuf:"bytes,3,opt,name=rotate,proto3,oneof"`
}

func (*Transaction_Register) isTransaction_Body() {}

func (*Transaction_Revoke) isTransaction_Body() {}

func (*Transaction_Rotate) isTransaction_Body() {}

type RegisterTx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *Certificate           `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTx) Reset() {
	*x = RegisterTx{}
	mi := &file_dpki_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTx) ProtoMessage() {}

func (x *RegisterTx) ProtoReflect() protoreflect.Message {
	mi := &file_dpki_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTx.ProtoReflect.Descriptor instead.
func (*RegisterTx) Descriptor() ([]byte, []int) {
	return file_dpki_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTx) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type RevokeTx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTx) Reset() {
	*x = RevokeTx{}
	mi := &file_dpki_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTx) ProtoMessage() {}

func (x *RevokeTx) ProtoReflect() protoreflect.Message {
	mi := &file_dpki_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTx.ProtoReflect.Descriptor instead.
func (*RevokeTx) Descriptor() ([]byte, []int) {
	return file_dpki_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeTx) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RevokeTx) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *RevokeTx) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RotateTx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	NewPublicKey  []byte                 `protobuf:"bytes,3,opt,name=new_public_key,json=newPublicKey,proto3" json:"new_public_key,omitempty"`
	NewAlgorithm  Algorithm              `protobuf:"varint,4,opt,name=new_algorithm,json=newAlgorithm,proto3,enum=dpki.v1.Algorithm" json:"new_algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateTx) Reset() {
	*x = RotateTx{}
	mi := &file_dpki_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateTx) ProtoMessage() {}

func (x *RotateTx) ProtoReflect() protoreflect.Message {
	mi := &file_dpki_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateTx.ProtoReflect.Descriptor instead.
func (*RotateTx) Descriptor() ([]byte, []int) {
	return file_dpki_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *RotateTx) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RotateTx) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *RotateTx) GetNewPublicKey() []byte {
	if x != nil {
		return x.NewPublicKey
	}
	return nil
}

func (x *RotateTx) GetNewAlgorithm() Algorithm {
	if x != nil {
		return x.NewAlgorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

var File_dpki_v1_transaction_proto protoreflect.FileDescriptor

const file_dpki_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"\x19dpki/v1/transaction.proto\x12\adpki.v1\x1a\x19dpki/v1/certificate.proto\"\xdb\x01\n" +
	"\vTransaction\x121\n" +
	"\bregister\x18\x01 \x01(\v2\x13.dpki.v1.RegisterTxH\x00R\bregister\x12+\n" +
	"\x06revoke\x18\x02 \x01(\v2\x11.dpki.v1.RevokeTxH\x00R\x06revoke\x12+\n" +
	"\x06rotate\x18\x03 \x01(\v2\x11.dpki.v1.RotateTxH\x00R\x06rotate\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\fR\tsignature\x12\x19\n" +
	"\bchain_id\x18\v \x01(\tR\achainIdB\x06\n" +
	"\x04body\"D\n" +
	"\n" +
	"RegisterTx\x126\n" +
	"\vcertificate\x18\x01 \x01(\v2\x14.dpki.v1.CertificateR\vcertificate\"P\n" +
	"\bRevokeTx\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x97\x01\n" +
	"\bRotateTx\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12$\n" +
	"\x0enew_public_key\x18\x03 \x01(\fR\fnewPublicKey\x127\n" +
	"\rnew_algorithm\x18\x04 \x01(\x0e2\x12.dpki.v1.AlgorithmR\fnewAlgorithmB6Z4github.com/ajablonsk1/blockchain-dpki/internal/typesb\x06proto3"

var (
	file_dpki_v1_transaction_proto_rawDescOnce sync.Once
	file_dpki_v1_transaction_proto_rawDescData []byte
)

func file_dpki_v1_transaction_proto_rawDescGZIP() []byte {
	file_dpki_v1_transaction_proto_rawDescOnce.Do(func() {
		file_dpki_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dpki_v1_transaction_proto_rawDesc), len(file_dpki_v1_transaction_proto_rawDesc)))
	})
	return file_dpki_v1_transaction_proto_rawDescData
}

var (
	file_dpki_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
	file_dpki_v1_transaction_proto_goTypes  = []any{
		(*Transaction)(nil), // 0: dpki.v1.Transaction
		(*RegisterTx)(nil),  // 1: dpki.v1.RegisterTx
		(*RevokeTx)(nil),    // 2: dpki.v1.RevokeTx
		(*RotateTx)(nil),    // 3: dpki.v1.RotateTx
		(*Certificate)(nil), // 4: dpki.v1.Certificate
		Algorithm(0),        // 5: dpki.v1.Algorithm
	}
)
var file_dpki_v1_transaction_proto_depIdxs = []int32{
	1, // 0: dpki.v1.Transaction.register:type_name -> dpki.v1.RegisterTx
	2, // 1: dpki.v1.Transaction.revoke:type_name -> dpki.v1.RevokeTx
	3, // 2: dpki.v1.Transaction.rotate:type_name -> dpki.v1.RotateTx
	4, // 3: dpki.v1.RegisterTx.certificate:type_name -> dpki.v1.Certificate
	5, // 4: dpki.v1.RotateTx.new_algorithm:type_name -> dpki.v1.Algorithm
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dpki_v1_transaction_proto_init() }
func file_dpki_v1_transaction_proto_init() {
	if File_dpki_v1_transaction_proto != nil {
		return
	}
	file_dpki_v1_certificate_proto_init()
	file_dpki_v1_transaction_proto_msgTypes[0].OneofWrappers = []any{
		(*Transaction_Register)(nil),
		(*Transaction_Revoke)(nil),
		(*Transaction_Rotate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dpki_v1_transaction_proto_rawDesc), len(file_dpki_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dpki_v1_transaction_proto_goTypes,
		DependencyIndexes: file_dpki_v1_transaction_proto_depIdxs,
		MessageInfos:      file_dpki_v1_transaction_proto_msgTypes,
	}.Build()
	File_dpki_v1_transaction_proto = out.File
	file_dpki_v1_transaction_proto_goTypes = nil
	file_dpki_v1_transaction_proto_depIdxs = nil
}
